office-for-students/wagtail-CMS

coursefinder/templates/coursefinder/course_finder_narrow_search.html
Remove disabled tags on the buttons in narrowing search by location
=> Enable narrow search buttons

.github/PULL_REQUEST_TEMPLATE.MD
Add github pull request template
=> Add github pull request template

courses/models.py
Refactor the data mapping in the course details model to protect against missing data points.
Go to https://test-discover-uni-cms.azurewebsites.net/course-details/10003645/UBLH4FJEWGW/Full-time/ and/or https://test-discover-uni-cms.azurewebsites.net/course-details/10007783/G100/Full-time/ to see the errors currently being experienced.
then go to the same courses whilst running the code locally to see the page now loading correctly.
=> protect against missing data points

widget/static/js/widget.js, widget/views.py
Removed hardcoded url domain from the widget code so it will point back to the correct site, rather than localhost.
Read the files, nothing to check locally as it will still point to localhost.
=> remove hard coding of widget button url domain

CMS/static/js/main.js, coursefinder/models.py, coursefinder/request_handler.py, coursefinder/templates/coursefinder/course_finder_postcode.html, coursefinder/templates/coursefinder/partials/course_finder_results_form.html, coursefinder/tests.py, coursefinder/views.py
Integrate the postcode in to the search query
Review the changes
=> apply select postcode to course finder results

CMS/settings/production.py
Added the secret env variable to the production environment settings.
Check the env variable has been correctly added to the production settings file.
=> prod env should pull the secret key from the env

CMS/static/js/feedback-form.js, CMS/templates/partials/feedback-form.html, CMS/urls.py, core/request_handler.py, core/views.py
The feedback form now submits through the CMS so the API auth token can be added to the request.
Go to any page and try to submit feedback
=> send feedback through the CMS server to enable API auth

CMS/static/jsonfiles/institutions.json
The institutions json file has been updated with latest data from UKRLP
Check the file carefully to ensure it meets the requirements.
=> Updated institutions.json file

dev_tools/build_institutions_json_file/README.md, dev_tools/build_institutions_json_file/build_institutions_json_file.py, dev_tools/build_institutions_json_file/requirements.txt
A Python tool that retrieves UKPRN data from CosmosDB and uses it to create an institutions.json file in the JSON structure required by the front end.
Review changes and test.
=> Tool to create institutions.json file

CMS/settings/production.py
Added allowed hosts for the production environments
Review the changes
=> add allowed hosts to the production settings

CMS/settings/production.py
Add domain name to production allowed hosts
Check changes make sense
=> Add domain name to allowed hosts for live service

CMS/urls.py, widget/templates/widget/iframe_widget.html
Set up a specific path that accepts a capital in the widget url.
Try to access the widget using a url with a capital W.
=> add specific path to handle capital w

CMS/static/js/search-dropdown.js
Change string parsing to handle ' in uni names
Review the change
=> use double quotes to allow for apostrophes in uni names

widget/static/js/widget.js
Downcase the language passed to the widget.
Look at the changes
=> make language keys case insensitive

CMS/static/js/google-analytics-tracking.js, CMS/templates/base.html
Add the GA tags to the base template
See that the scripts are in place
=> add google analytics code to the site

CMS/templates/base.html, core/models.py
See title
Check pages in context adds title to title tag. May need to add a title for the slug in CMS
=> Add page to context to use title tag in dynamic pages

coursefinder/templates/coursefinder/course_finder_base.html, coursefinder/templates/coursefinder/course_finder_results.html
See title; `<li>` should be the first tag in `<ul> or <ol>` tag
Check changes do not break design
=> Correct sematically incorrect list mark-up

courses/views.py
Replace the {{institution_name}} in a course details links header on page load.
=> inject the uni name in to the string

CMS/static/js/filters.js, CMS/templates/_pagination.html, coursefinder/models.py, coursefinder/templates/coursefinder/partials/filters.html
Page changes now submit a post request to maintain filters
Go to the results page and apply some filters (not so many that there is only one page).
Click on one of the page change buttons.
You should be taken to the next set of results and the filters should still be applied.
=> update pagination to work using post requests

coursefinder/forms.py
Remove quotes from institution names passed in to filters
Search for a university.
Add a filter on the results page
The results list should still just contain the searched for uni.
=> remove quotes from institution when passing into results form

CMS/static/js/filters.js, CMS/static/js/main.js
Update the reading of the institution JSON to mirror new structure.
Load any page, check the institutions have been loaded in to the local storage.
=> handle new JSON structure for institutions

CMS/settings/production.py
Missing www test domain name from CMS production settings
check syntax
=> Add missing domain name from CMS production settings

courses/static/js/label_explanation_popups.js, courses/static/scss/course_detail.scss, courses/templates/courses/course_comparison_page.html, courses/templates/courses/course_detail_content.html, courses/templates/courses/partials/after_one_year_body.html, courses/templates/courses/partials/after_the_course_body.html, courses/templates/courses/partials/comparison_after_one_year_body.html, courses/templates/courses/partials/comparison_after_the_course_body.html, courses/templates/courses/partials/comparison_entry_information_body.html, courses/templates/courses/partials/entry_information_body.html, institutions/static/js/institution_explanation_pop_ups.js, institutions/templates/institutions/partials/explanation_pop_up.html
Fix accessibility focus order failure
=> fix focusing on popups

CMS/templates/partials/cookie-banner.html
Fixed the routing to the welsh cookies page.
=> set correct path for cookies page

coursefinder/views.py
Use the fixed links on both welsh and english routes
=> fixed paths need to use fixed paths in welsh as well

CMS/static/js/filters.js, CMS/static/js/main.js
Fix the order of steps to load uni JSON so it has it at the right time.
Go to the results page and try to navigate to the second page, the second page should load correctly.
=> fix the loading of uni JSON

institutions/models.py
Stop the frontend from trying to correctly capitalise uni names (it was failing at it anyway).
This is going to be handled in the API.
Read the change
=> don't format insitution name, the data api will do it

CMS/settings/production.py
Added the new write pre prod env domain to allowed hosts.
Read the change.
=> add write domain to allowed hosts

holding-page-azure-pipelines.yml
Added a pipeline definition for the holding page
=> add build definition

CMS/translations.py
All of the changes are due to casing, here I've tried to cover for both scenrios, sentence case and when the first letter of each word is capitalised.
Check file is structured correctly
=> Add missing translation mappings

content/static/scss/content.scss, coursefinder/static/scss/course_finder.scss
Fixed issue where background images moved and grew using drop-down selects.
=> fix to bkg images moving and growing

courses/static/scss/student_satisfaction.scss
Fixed issue where circle charts did not line up in Student Satisfaction
=> fixed circle heights

coursefinder/static/scss/course_finder.scss
Fixed ipad issue having to double click 'next' buttons in course finder
=> fix to ipad double click on buttons

CMS/static/js/main.js
Don't show red bookmark notification if there aren't any bookmarks
=> only show bookmark notification if more than 0

site_search/static/scss/search_landing.scss, site_search/templates/site_search/search_landing_page.html
Changed search landing page logo, removed text input labels and replaced with placeholders
=> updated search landing logo and added placeholder text

CMS/static/js/main.js
Fix for course finder drop down not working in IE
=> added polyfill for ie

CMS/static/jsonfiles/institutions.json
See title
If you have access to azure search in the Azure Portal, you can take the institution name from the new file and test whether it is filterable. Or easier still use API Management and use the search endpoint to search by institution name from the new file and you should get results for that institution only, use the query parameter `institutions`.
Otherwise allow this to go through and we can create a release branch so it is built in pre-prod to check it fixes the staging environment.
=> Upload new instituiton list of names for search drop down

CMS/settings/production.py, CMS/static/jsonfiles/institutions.json, dev_tools/build_institutions_json_file/README.md
README.md updated and upload new institutions.json file
Check nothing has gone in that shouldn't have
=> Update build institutions json script README.md

content/static/scss/section.scss, content/templates/content/section.html
Implemented the styling for the related links sections.
Go to a content page with related links present. The UI should now match the designs in figma.
=> add styling for the related links areas

CMS/settings/base.py, CMS/settings/production.py
Enabled several security settings in the production config
=> enable security settings

courses/views.py
Fixed the language toggle for the compare page.
=> use the linked translated page for link

CMS/static/js/main.js
Have made the bookmark count hide when the count goes to 0
=> hide bookmark count

CMS/settings/base.py, CMS/settings/production.py
Added package to allow CMS to interact with Cloudflare.
=> add cloud flare integration in to cms

courses/templates/courses/partials/comparison_student_satisfaction_body.html
Remove duplicated code.
Read the change
=> remove duplicate disclaimers

CMS/translations.py, courses/templates/courses/partials/course_overview.html, courses/templates/courses/partials/unavailable_disclaimer.html
Added in extra translations for Welsh
=> add missing welsh translations

CMS/templates/partials/course_result.html
Put in welsh translations for search results
=> translate search results content

CMS/static/js/main.js
Fix the search dropdown type ahead
=> fix id look up

dev_tools/subjectcodes/Makefile, dev_tools/subjectcodes/README.md, dev_tools/subjectcodes/english-and-welsh-subject-names.csv, dev_tools/subjectcodes/main.go
Add script to create subject codes json file
follow README.md instructions to run the script (fyi - it is written in go)
=> Add subject codes script

CMS/translations.py, courses/static/js/doughnut_chart.js
Added translations for graph accessibility
=> add welsh translations for accessible graphs

CMS/static/js/main.js
Anonymize GA collected IP addresses.
Read the change
=> add anonymize ip param to ga config

core/templatetags/discover_uni_tags.py
Refactored to new string injection method to avoid welsh characters
=> refactor to new injection method

deploy_files/docker-entrypoint-readonly.sh
Added a startup script for the read only servers that doesn't try to migrate the db.
=> add read only server start up script

courses/templates/courses/partials/after_one_year_body.html, courses/templates/courses/partials/after_the_course_body.html, courses/templates/courses/partials/comparison_after_one_year_body.html, courses/templates/courses/partials/comparison_after_the_course_body.html, courses/templates/courses/partials/comparison_entry_information_body.html, courses/templates/courses/partials/entry_information_body.html
Fixed missing labels by repairing the "label" tag and adding the "get_translation" method.
=> Fix for missing labels

deploy_files/docker-entrypoint-readonly.sh, deploy_files/docker-entrypoint.sh
Add max requests setting to the gunicorn settings
=> add worker recycle setting to gunicorn

CMS/settings/production.py
Added new widget domains to allowed list
=> add new widget domains to allowed list

.gitignore, courses/static/js/manage-bookmarks.js
Added "local.py" to .gitignore.
Refactored bookmark fix.
=> Added ignore for locally loaded settings. Improved fix for bookmarks.

deploy_files/Dockerfile
Lock python version to ensure package compatibility
=> lock python version

widget/urls.py
Unis don't read documentation, so we are handling the url they are actually using.
=> handle the url the unis are using for the widgets, despite the guidance

requirements.txt
Locked the version of wagtail to ensure dependency compatibility
=> fix version of wagtail

courses/models.py, courses/static/js/course_comparison.js
Now the bookmark stored data has mode in English and Welsh the value has to be read from one layer deeper.
=> update compare functionality to work with new bookmark data structure

courses/static/js/course_comparison.js
Make the course selectors work with both the new and the old data format to make the tool compatible with existing bookmarks and new ones.
=> Compare compatibility

CMS/welsh_urls.py
Added in the welsh url for the compare page that had been missed out
=> add in the welsh url for the comparison page

courses/models.py
=> Prevent internal server error by accessing non existent links object.

institutions/models.py, institutions/templates/institutions/institution_detail_page.html
=> Fix for institution that lack any student union websites.

site_search/models.py, site_search/static/scss/search_landing.scss, site_search/templates/site_search/search_landing_page.html
=> Added search disclaimer for Welsh search page.

site_search/static/scss/search_landing.scss
=> Added margin to disclaimer.

requirements.txt
=> Revert wagtail version.

coursefinder/templates/coursefinder/partials/filters.html
=> Correctly fetching page and result counts in filter form.

courses/static/js/compare-selector.js, courses/static/js/manage-bookmarks.js
=> Added default value for course mode.

coursefinder/views.py
=> Added missing import

courses/templates/courses/course_detail_content.html
=> Hidden div containing dummy buttons on course detail page

courses/urls.py
=> Added $ to parsed characters in course id url

CMS/templates/partials/institution_result.html
=> Removed title method from institution Title due to wrong capitalization

courses/models.py, institutions/models.py
=> Added support for welsh institution names in models

CMS/static/scss/partials/filters.scss, CMS/translations.py
=> Missing Welsh translation in Filter

CMS/static/scss/partials/filters.scss, CMS/translations.py, coursefinder/templates/coursefinder/partials/filters.html, site_search/models.py, site_search/templates/site_search/search_landing_page.html
=> Added missing Welsh translations to filter

coursefinder/templates/coursefinder/partials/filters.html
=> Enabled qualification filter labels.

CMS/templates/partials/nav.html
=> Search Button Icon in Welsh

CMS/static/scss/partials/compare.scss, CMS/static/scss/partials/nav.scss, coursefinder/templates/coursefinder/course_finder_base.html
=> Internet Explorer styling issues

CMS/static/scss/global.scss, CMS/templates/base.html, CMS/translations.py, home/static/scss/home.scss, home/templates/home/home_page.html
=> Removed Covid19 image and replaced it with a banner

CMS/static/scss/partials/footer.scss
=> Fixed left padding not reseting for desktop on brand logo.

CMS/static/js/main.js
=> Revert change on subjectQuery field

CMS/static/js/main.js, CMS/static/scss/partials/search_dropdown.scss, CMS/templates/partials/search-dropdown.html
=> Normalized styling

README.md
=> Added new environment variables to README

CMS/templates/_pagination.html, coursefinder/templates/coursefinder/partials/filters.html
=> Fixed pagination redirection in case of first page.

CMS/templates/_pagination.html
=> Fixed some additional links.

institutions/templates/institutions/institution_detail_page.html
=> Switched action used by form.

CMS/static/js/filters.js, courses/static/js/back-button.js, courses/static/scss/course_detail.scss, courses/templates/courses/partials/course_overview.html
=> Added support for all filter fields.

CMS/static/js/main.js
=> Removed code error on main.js for subject area

courses/templates/courses/partials/course_overview.html
=> Fixed missing form id on welsh.

CMS/static/js/filters.js
=> Fixed missing case for welsh default subject dropdown value.

coursefinder/views.py
=> Enabled qualification filters

CMS/static/scss/partials/pagination.scss, coursefinder/views.py
CSS styling fix for pagination in IE. 
Removed obsolete strip  applied to mode_query filter.
=> Fix for OFS-64

CMS/static/scss/global.scss, CMS/templates/base.html
Styling changes to the banner.
=> Styling changes as per client request.

CMS/static/scss/global.scss
Styling changes to exclamation mark.
=> Styling changes to exclamation mark.

CMS/templates/base.html
Added site improve tracking to the HTML Head.
Ensure the script exists in the head of the pages (sits underneath <script async="" src="https://www.googletagmanager.com/gtag/js?id=UA-147556197-1"></script>)
=> added tracking link as provided on the ticket.

courses/static/js/compare-selector.js
Allows same provider, same course with different study mode to be bookmarked.
Ensure that a course with the same provider and course id, but different study modes can be bookmarked. Examples below:
http://localhost:8000/course-details/10000381/BAMT/Full-time/
http://localhost:8000/course-details/10000381/BAMT/Part-time/
=> Added comparison for study mode 

CMS/templates/base.html, courses/static/js/compare-selector.js
See branch bug/ofs-158 .. for details.
=> Add additional fix for 158 - mode comparison.

institutions/static/scss/institution_details.scss
=> Resize TEF link image

institutions/static/scss/institution_details.scss
Added a css width constraint on a new selector, on institution details page inside TEF ratings explained.
=> added css for inner tef rating images

CMS/static/scss/global.scss, home/static/scss/home.scss
Resized the video on the landing page. CSS changes only.
=> Temporary fix for video until a new how-to page is created.

content/templates/content/flat_content.html
Added script embedding custom survey prepared by OFS.
Check that the survey is correctly displayed and formatted on this page:
http://localhost:8000/teachers-and-advisers/advisers-and-teachers-feedback-survey/
Check that the survey is not displayed on other pages.
=> Embedded survey script link.

courses/static/js/back-button.js, courses/templates/courses/partials/course_overview.html
Removed form surrounding back button.
=> back button fix

CMS/translations.py, home/templates/partials/home_page_content.html
Merge fix for incorrect URLS on home page.
=> incorrect links

manage.py
Alter flag in manage.py for release.
=> change flag in manage.py

content/static/scss/section.scss
*Change - Center the text on additional links wrapper.
=> center the text on additional links wrapper

CMS/static/jsonfiles/institutions_cy.json, CMS/static/jsonfiles/institutions_en.json
Updated the names of various institutes for the search
On the homepage search for `Waterbear` in the `All universities and colleges` drop-down text field. If the institute shows up then the code works
=> Used latest institution lookup files provided by OfS.

CMS/static/jsonfiles/institutions_cy.json
Updated institutions lookup files. Release planned for all 3 environments.
=> Revert Penybont to Bridgend.

CMS/static/jsonfiles/institutions_cy.json
Added the welsh name for Bridgend College
Go to localhost:8000, change the language to welsh and search for the institute "coleg" in the text search pulldown
=> changed Bridgend College to Colge Penybont in the institutions_cy.json

CMS/templates/base.html
Added script for siteimprove.
Check that the script exists inside the <head> tag. No way to test script working until on prod. (Has previously been tested with the same script).
=> added missing script for siteimprove

coursefinder/static/js/button-visibility.js, coursefinder/templates/coursefinder/course_finder_results.html, courses/static/js/back-button.js, courses/templates/courses/course_manage_page.html, courses/templates/courses/partials/course_overview.html
Dynamically hide the back button if the user does not come from the bookmarks or course search page. (Code mostly as per previous implementation by Methods). 
Open a course by clicking a link from the bookmarks page and then on the course page, check that the back button does exist. Do the same for the course search page.
Copy the link address of a course page and open in a new window, check that the back button isn't shown.
=> dynamically hide back button

courses/models.py
The fix for the "LLB" course for University of Stirling has been reverted
Go to the following pages to view the changes:
http://localhost:8000/course-details/10007804/U18-LAWLLB/Full-time/
https://dev-discover-uni2.azurewebsites.net/course-details/10007804/U18-LAWLLB/Full-time/
=> removed LLB Law Sterling fix

courses/models.py, courses/templates/courses/partials/comparison_earnings_after_the_course_body.html, courses/templates/courses/partials/earnings_after_the_course_body.html
Made it so the title of the course salary is based on the currently selected language
https://dev-discover-uni2.azurewebsites.net/course-details/10007783/LQ63/Full-time/
=> added a language dependent title for subject salaries

CMS/static/jsonfiles/institutions_cy.json, CMS/static/jsonfiles/institutions_en.json
Updated the institutions json files
"British College of Osteopathic Medicine " -> "British College Of Osteopathic Medicine "
http://localhost:8000/institution-details/10000911/
"Icon College of Technology & Management" -> "ICON College of Technology & Management "
http://localhost:8000/institution-details/10003239/
"Jca | London Fashion Academy " -> "JCA | London Fashion Academy "
http://localhost:8000/institution-details/10067601/
=> updated institution json files

CMS/static/jsonfiles/institutions_cy.json, CMS/static/jsonfiles/institutions_en.json
=> updated json files

CMS/settings/dev.py, CMS/settings/pre-production.py, CMS/settings/production.py, CMS/urls.py
added url /env-check/ to see what settings files are being loaded
go to /env-check/ and see if the page loads
=> added url /env-check/ to see what settings files are being loaded

README-short.md
Update `README-short.md` to include how to handle the scenario when developer is presented with the `wagtailforms_formsubmission` message during initial setup.
=> Handle wagtailforms_formsubmission during initial during setup

CMS/static/scss/partials/filters.scss, CMS/templates/partials/institution_results.html, CMS/translations.py
A message indicating no courses were found with the currently applied filters.
=> no results, translation and styling

CMS/static/scss/partials/filters.scss
Apply filters button now uses position: fixed on mobile screens to keep the button at the bottom of the screen. 
Adjusted the padding so the button matches the filter accordions.
=> apply filters button mobile fix

coursefinder/templates/coursefinder/partials/study_mode_filters.html
Enable Study Mode on campus filter option - https://app.clickup.com/t/f76egb
Depends on https://github.com/office-for-students/beta-search-api/pull/47
=> Enable on_campus filter option

CMS/static/js/filters.js, CMS/translations.py, coursefinder/templates/coursefinder/partials/active_filters.html
Added On campus to the clear filters JS.
=> added on-campus to the clear filters

CMS/static/js/filters.js, coursefinder/templates/coursefinder/course_finder_results.html, coursefinder/templates/coursefinder/partials/active_filters.html, coursefinder/templates/coursefinder/partials/filters.html
Course and institution dropdown selection now appear in the filter pills.
New functions have been created so that the course and institution are now remembered on submit of the filter form.
Course and institution can be removed separately using the filter pills.
=> course and institution now appear in the filter pills

coursefinder/templates/coursefinder/partials/active_filters.html
A fix to stop [""] getting sent to the institution query when removed using the filter pills.
=> institution search query fix

CMS/static/scss/partials/filters.scss
Added a larger margin underneath the no courses message
=> bigger margin under no courses message

CMS/translations.py, coursefinder/templates/coursefinder/course_finder_results.html
Added translation and changed the text on the search button on the course finder results page.
=> new search box

CMS/static/scss/partials/filters.scss, CMS/templates/search_results_list.html, coursefinder/static/scss/course_finder.scss
The bottom of the page is now pushed down if the filter list exceeds the length of the results accordions.
=> page now responsive to filter size

CMS/templates/partials/institution_results.html, coursefinder/static/scss/course_finder.scss
Results accordions now fit the frame of the website.
=> results accordions flex width set

CMS/templates/partials/institution_result.html, coursefinder/templates/coursefinder/partials/active_filters.html
Fixed font size on multiple screen sizes for the "- distance learning" labels.
=> fixed styling on different screen sizes

coursefinder/templates/coursefinder/partials/active_filters.html
Fix for removing courses when the institution query is empty.
=> institution filter pill fix

coursefinder/templates/coursefinder/partials/active_filters.html
Put quotation marks around the subject search
=> added quotation marks to subject pill

CMS/translations.py
Updated the translation for no courses message.
=> updated translation

CMS/templates/partials/new-search-dropdown.html
Adjusted the class name so the search function now detects the institution dropdown menu.
=> dropdown search fix

README-short.md
Update secrets reference in README
=> Update location of secrets

CMS/static/js/filters.js, coursefinder/static/js/active-filter-pills.js, coursefinder/templates/coursefinder/partials/active_filters.html
Changes sort by subject to false when removing a filter using the filter pills.
Returns sort by subject = false when clicking the apply filters button.
=> Mx6959 default to institutions when filter removed

coursefinder/request_handler.py
Converted the request in requests.py to get the institutions list as JSON
=> convert institutions request to json

coursefinder/request_handler.py
Changed request method to POST.
=> change request to post

CMS/templates/partials/search_results.html
Added a margin between single subject courses and multiple subject courses
=> add margins between section

CMS/static/js/filters.js, CMS/static/scss/partials/filters.scss, CMS/templates/partials/search_results.html, coursefinder/static/scss/course_finder.scss
Added a margin-top on the spinner and have hidden the pagination while the sort by subject page is loading.
=> moved spinner and hide pagination on load

coursefinder/templates/coursefinder/partials/active_filters.html
replaced all special character codes with their respective characters.
=> remove course fix

CMS/templates/partials/new-search-dropdown.html
institutions dropdown now opens on click or on focus.
=> dropdown opens on focus

CMS/static/js/main.js, coursefinder/templates/coursefinder/partials/location_filters.html, coursefinder/templates/coursefinder/partials/study_mode_filters.html
Changed main.js and the individual filter html files so that the filter accordions are open by default.
=> filters are now open by default

README-quick-start.md, README-short.md
A bare minimum stet of steps to set up the dev environment from scratch
=> Add README-quick-start.md

coursefinder/templates/coursefinder/course_finder_results.html
The previously searched course now appears in the course search bar.
=> previous course query now in search bar

CMS/templates/partials/new-search-dropdown.html
https://app.clickup.com/t/p3brcf 
Open in browser and confirm on media sizes that this performs correctly.
=> Fix movement on page when the search drop down is opened

CMS/static/scss/partials/filters.scss, CMS/templates/partials/new-search-dropdown.html
Remove the last bit of movement. Remove border, replace with shadow and adjust dropdown so it looks like it did before
open in browser and compare with prod
=> https://app.clickup.com/t/p3brcf

CMS/templates/partials/new-search-dropdown.html
As per https://app.clickup.com/t/p3brcf discussion. Show one name or number of selected insinuations 
Pull and check that when an institution is selected that the text is displayed over one line reflecting the above.
=> Show one name or number of selected insinuations 

courses/static/js/arrows.js, courses/templates/courses/course_comparison_page.html
=> discovered bug where you could scroll beyond the available courses.

courses/static/js/ratings.js, courses/static/js/responsive_comparison.js, courses/static/scss/course_comparison.scss, courses/templates/courses/partials/comparison_courses_row.html, courses/templates/courses/partials/course_comparison_overview.html
Fix typo In class name row > column. Remove width ins css, was preventing it from being responsive
=> Sjh responsive arrows

courses/static/js/responsive_comparison.js, courses/static/scss/course_comparison.scss
height of cards, space between cards and course details. Update sticky headers when cards height is different
=> Responsive styling fixes

CMS/translations.py, courses/static/scss/course_comparison.scss, courses/templates/courses/course_manage_page.html
Padding changes on columns, capitalised "Course comparison", fixed local storage on removing a course.
=> padding fix, capital letter fix, compare courses fix.

courses/renderer/comparison.py
add back in the accordion headers (placeholders) pending that released tickets completion.
=> Add back in all seven accordions

courses/static/js/manage-bookmarks.js, courses/static/js/ratings.js, courses/static/js/responsive_comparison.js, courses/templates/courses/course_comparison_page.html, courses/templates/courses/course_manage_page.html, courses/views.py
General fixes after testing tickets
=> course-comparison

courses/views.py
Fix nav urls for course comparison
=> fix broken urls to make translations work

CMS/translations.py, courses/renderer/comparison.py, courses/static/scss/manage_bookmarks.scss
Fix arrow position when no course bookmarked
Add Welsh translations to Accordions
=> Sprint 1 fixes

CMS/translations.py, courses/static/js/ratings.js, courses/static/scss/course_comparison.scss
Fixed a link in the earnings and employment accordions.
=> fixed link, removed dataIndex from ratings added display block

CMS/static/js/accordion.js, CMS/templates/partials/course_result.html, CMS/urls.py, courses/static/js/bookmark_management.js, courses/static/js/compare-selector.js, courses/static/js/ratings.js, courses/static/js/responsive_comparison.js, courses/templates/courses/comparison/comparison_has_courses.html, courses/templates/courses/course_comparison_page.html, courses/templates/courses/course_detail_content.html, courses/templates/courses/course_manage_page.html, courses/templates/courses/partials/course_comparison_overview.html, courses/views/comparison_body.py
Fix issue when closing courses for comparison. 
- Deselecting a  course returned on page refresh
- Arrows not always updating based on content
- Sticky headers being responsive on card height changes when course are deselected
Review against non local data to ensure the course ids are generated correctly. 
Download an run against pre-prod data
=> Feature fixes localstorage

CMS/translations.py, courses/templates/courses/partials/subject_selector.html
Added translations for the subject selector
=> added translations for subject_selector.html

CMS/translations.py, courses/request_handler.py, courses/views/comparison_body.py
Readded the compare courses header
=> re-added compare heading and removed prints

courses/static/js/course_comparison.js
=> Remove reference to index of local storage in ratings

CMS/static/scss/partials/nav.scss
New nav bar matching the design of Zeplin to be merged into the show and tell branch
=> Feature h318gn jb

CMS/settings/base.py, CMS/static/images/new.svg, CMS/translations.py, home/static/assets/new.svg, home/templates/partials/home_page_content.html
- Added finder helper for Youtube embed URLS for ticket p9euw2
- Add new logo for information box on home page 1c239nk
=> updated urls, added new icon, added embed finder helper

courses/static/scss/course_comparison.scss
=> decreased the margins between each row

CMS/static/scss/partials/nav.scss
=> fix compare menu padding

courses/static/js/course_comparison.js, courses/templates/courses/comparison/comparison_has_courses.html
=> update sleceted course on the mobile view

CMS/test/mocks/course_format_mocks_content.py, courses/static/js/course_comparison.js, courses/static/scss/accordions.scss, courses/static/scss/course_comparison.scss, courses/static/scss/manage_bookmarks.scss, courses/templates/courses/comparison/comparison_has_courses.html, courses/templates/courses/course_manage_page.html, courses/views/comparison_body.py
Style changes and additional media queries to free up more space on smaller screens
On the course comparison page, server returns 206 if no courses are selected and the Javascript for the course comparison isn't initialised.
PR now to merge in with @nickpatti working branch to get conflicts out of the way. 
Ticket still in progress
=> Sjh #pxc6vb

CMS/context_processors/nav_context_processor.py, courses/static/scss/course_comparison.scss
fix stars not being orange
fix navigation
=> fix broken nav

CMS/static/js/main.js, courses/static/js/bookmark_management.js, courses/static/js/compare-selector.js
Fixes bookmark count on nav bar - now reflects actions that take place on the search results and bookmark page and the course details page
=> Sjh js nav bugfix

CMS/static/scss/partials/nav.scss, courses/static/js/course_comparison.js
#1d4da96
Download, open In browser and confirm that the accordion header remains pinned to the top(or the course cards) as you scroll through the page.
=> Fixe accordion header being hidden when scrolling

CMS/static/scss/partials/nav.scss, CMS/templates/partials/nav.html
Fix dropdown show/hide on load
=> fixes dropdown to be hidden on load

courses/static/scss/course_comparison.scss
increase card name font size on bigger screens
=> increase title size and remove commented out scss

courses/static/scss/course_comparison.scss, courses/templates/courses/course_comparison_page.html
Needs to be display flex to enable the hide and show at the right time
=> should be flex

CMS/translations.py, courses/static/scss/course_comparison.scss, courses/templates/courses/partials/accordion_body.html
=> guidance box links open in new tab.

CMS/static/scss/global.scss, CMS/static/scss/partials/compare.scss, CMS/static/scss/partials/filters.scss, CMS/static/scss/partials/search_dropdown.scss, content/static/scss/flat-content.scss, content/static/scss/section.scss, coursefinder/static/scss/course_finder.scss, courses/static/scss/accordions.scss, courses/static/scss/accreditation.scss, courses/static/scss/after_one_year.scss, courses/static/scss/course_comparison.scss, courses/static/scss/course_detail.scss, courses/static/scss/earnings_after_course.scss, courses/static/scss/employment_after_course.scss, courses/static/scss/entry_information.scss, courses/static/scss/graduate_perceptions.scss, courses/static/scss/manage_bookmarks.scss, courses/static/scss/student_satisfaction.scss
=> changed em to rem

courses/static/scss/course_comparison.scss, courses/templates/courses/partials/course_comparison_overview.html
Title of course on the course comparison page now links to the course details page.
=> course title is now a link to course details

courses/views/views.py, institutions/views.py
Fixed pages linking incorrectly when clicking the welsh translation in the nav.
=> fixed translated links

courses/templates/courses/course_manage_page.html
Remove unexpected character in JS file
=> remove unexpected character

courses/templates/courses/partials/course_overview.html, courses/templates/courses/partials/links_to_the_institution_website_body.html, courses/templates/courses/partials/professional_accreditation_body.html
- Added target blank to links on course detail page body
=> added links opening in new tab to course detail page

home/models.py
Added filter form as empty dictionary to home page context
=> Added filter form to home page context

CMS/templates/partials/new-search-dropdown.html, home/models.py, home/templates/partials/home_page_content.html
Home page avoids using filter form in the dropdown menu.
=> render search dropdown differently if on home page

coursefinder/templates/coursefinder/partials/coursesearch/searchbox.html, home/models.py
is_welsh removed and language added to context of home page
=> language fix

CMS/static/scss/partials/feedback_form.scss, CMS/translations.py, courses/renderer/comparison.py, courses/renderer/sections/continuation.py, courses/renderer/sections/entry.py, courses/renderer/sections/satisfaction.py, courses/static/scss/course_comparison.scss, courses/templates/courses/partials/accordion_body.html, courses/templates/courses/partials/comparison_courses_row.html
Multiple subjects now display on all accordions except for the institution links.
https://app.clickup.com/t/1ecb806
Second entry information accordion updated from "After 3 years", to "UCAS tariff points"
https://app.clickup.com/t/1ecdth0
=> Multiple subject fix

CMS/translations.py, courses/models/continuationstatistics.py, courses/models/employmentstatistics.py, courses/models/entrystatistics.py, courses/models/graduateperceptionstats.py, courses/models/jobtypestats.py, courses/models/satisfactionstats.py, courses/models/tariffstats.py, courses/models/utils.py, courses/renderer/comparison.py, courses/renderer/sections/base.py, courses/renderer/sections/continuation.py, courses/renderer/sections/course_details.py, courses/renderer/sections/earnings.py, courses/renderer/sections/employment.py, courses/renderer/sections/entry.py, courses/renderer/sections/graduate_perception.py, courses/renderer/sections/satisfaction.py, courses/static/scss/course_comparison.scss, courses/templates/courses/partials/accordion_body.html, courses/templates/courses/partials/comparison_courses_row.html
Updated unavailable messages:
Unavailable function is now a shared function, rather than being redefined in all models.
Body of the messages are now taken from the model.
Aggregation messages are now displaying the correct subject names.
Satisfaction aggregation row has been added.
Unavailable messages have been added to each sub-accordion, and pull from the correct array.
Unavailable messages for the Earnings sub-accordion have been updated.
Optional distance learning added to the course details section.
=> Unavailable messages ndp

courses/models/employmentstatistics.py, courses/models/graduateperceptionstats.py, courses/models/utils.py
Get unavailable reason header and body first, then replace the body value dependant on aggregation level.
=> fixed course details unavailable messages.

courses/models/utils.py
"Over two years" now replaced in the reason_header, rather than the reason_body.
=> changed from body to heading replace

courses/models/course.py, courses/renderer/comparison.py, courses/renderer/sections/base.py, courses/renderer/sections/continuation.py, courses/renderer/sections/employment.py, courses/renderer/sections/graduate_perception.py, courses/renderer/sections/unavailable.py, courses/renderer/sections/unavailable_dict.py
Unavailable headers now switch.
"No data available" persists for the whole column.
"No data available" removed from the tool tip.
=> Unavailable fixes

CMS/static/js/search_box.js, CMS/templates/partials/new-search-dropdown.html
- Fix JS for institution dropdown so behaviour matches prod
=> Fix institution dd

courses/models/salary.py, courses/renderer/comparison.py, courses/renderer/sections/course_details.py, courses/renderer/sections/earnings.py, courses/renderer/sections/employment.py, courses/static/scss/course_comparison.scss, courses/templates/courses/partials/accordion_body.html, courses/templates/courses/partials/comparison_courses_row.html
- Response rate added for employment after three months sub-accordions.
- Course length is blank when = 0 years.
=> Grad outcomes response rate

courses/renderer/sections/earnings.py, courses/views/translate.py
=> Comment out print statements

courses/renderer/sections/earnings.py, courses/static/js/course_comparison.js
Nothern Ireland courses now say "no data available" instead of None
=> earnings northern ireland unavailable fix

courses/renderer/comparison.py
No data available on multiple subjects fixed.
=> No data available changed to this course

CMS/translations/dictionaries/general.py, CMS/translations/dictionaries/unavailable.py, courses/renderer/comparison.py, courses/templates/courses/partials/subject_selector.html
"This course" fix moved to template.
Override added for graduate and employment accordions.
=> Subject no data fix

courses/renderer/sections/base.py, courses/renderer/sections/employment.py, courses/renderer/sections/graduate_perception.py, courses/renderer/sections/unavailable.py
index passed into get_unavailable to display correct unavailable message.
=> index passed into get_unavailable

CMS/translations/dictionaries/general.py, courses/templates/courses/partials/course_overview.html
student_satisfaction in this content should not be National Student Survey
=> Student Satisfaction title remains

courses/models/continuationstatistics.py, courses/models/employmentstatistics.py, courses/models/entrystatistics.py, courses/models/graduateperceptionstats.py, courses/models/jobtypestats.py, courses/models/satisfactionstats.py, courses/models/tariffstats.py, courses/models/utils.py
Added a requested tweak to the Welsh translation.
=> welsh unavailable header update

CMS/translations/dictionaries/general.py
Update guidance url in info box on course comparison
=> update guidance url

courses/templates/courses/partials/course_overview.html
Removed the double course title, removed target=blank
=> Info boxes fix

CMS/translations/dictionaries/general.py, CMS/translations/dictionaries/statistics.py
- FIxed course detail main info box typo
- Changed translations for graduate perceptions and earnings 15 months accordions to match requirements
=> corrected info boxes as per requirements

courses/models/salary.py, courses/models/sectorsalary.py
Replace all dictionary lookups in Salary with get
=> replace all dictionary lookups with get

CMS/translations/dictionaries/general.py
=> Fix info box

courses/static/scss/course_detail.scss
HighCharts.js changed this afternoon. Hotfix to resolve visual artefacts on course details page.
=> fix charts

CMS/translations/dictionaries/general.py, courses/renderer/sections/earnings.py, courses/templates/courses/partials/country_population.html
- Corrected the "Find out more" link on the course comparison page.
- Added the institution name to the earnings accordion.
- Run locally and click the find out more link.
- Compare courses that have data available, and check the institution name is being displayed.
=> Ndp 1fmkbz2 1fztxpa

CMS/translations/dictionaries/general.py, courses/static/scss/after_one_year.scss, courses/static/scss/course_detail.scss, courses/static/scss/employment_after_course.scss, courses/static/scss/entry_information.scss, courses/static/scss/student_satisfaction.scss, courses/templates/courses/partials/doughnut_chart.html, courses/templates/courses/partials/student_satisfaction_body.html
-Fixed spacing around the pie charts
-All final students text removed
-Fixed line spacing of employment section
-Corrected capitalisation
-Corrected text alignment on the course details page
-Corrected all font inconsistencies.
=> Ndp 1hytbuy 1hyt4hr 9cqx8v

home/static/scss/home.scss
gradient stopped short on home page
extend across entire homepage
=> fix odd gradient that stopped halfway across page

CMS/settings/base.py, CMS/templates/robots.txt, CMS/urls.py, core/views.py
Add basic sitemap and robots.txt
Have additional ticket to expand sitemap creation to incorporate dynamic content.
=> Add initial sitemap and robots.txt

courses/renderer/sections/earnings.py
- Moved institution name as per ticket requirements
=> positioned institution from earnings after above data from people

institutions/templates/institutions/institution_detail_page.html
changed link to ukprn instead of pubukprn
added welsh translation
=> Fixed OFS register link and added welsh translation - #2p6308

institutions/templates/institutions/institution_detail_page.html
=> Added more logic to register link - #2p6308

institutions/templates/institutions/institution_detail_page.html
changed small typo of OFS to OfS
=> changed small typo

courses/renderer/comparison.py, courses/templates/courses/partials/course_overview.html, courses/templates/courses/partials/earnings_after_the_course_body.html
HOTFIX - Leo data is being updated. Creating a release branch from master to avoid DJANGo upgrade changes. Merging in to release branch.
=> Sjh remove leo data #2f3mqj6

CMS/static/scss/global.scss, courses/templates/courses/course_detail_content.html
changing a tag hover colour bug
=> change to a tag hover colour - #2ff554r

CMS/templates/base.html
add description to wagtail pages
=> read in the description from wagtail

coursefinder/templates/coursefinder/partials/coursesearch/search_box_right_side.html, coursefinder/templates/coursefinder/partials/coursesearch/searchbox.html, courses/templates/courses/partials/comparison/course_search_container.html, home/static/scss/home.scss
fixed sizing issue for homepage search box section 
https://app.clickup.com/t/2he1hm2
=> sizing problem for mobile screens fixed

courses/static/scss/course_detail.scss
added orientation landscape to media query
https://app.clickup.com/t/284928v
=> added orientation: landscape to media query

courses/static/scss/course_detail.scss, home/static/scss/home.scss, home/templates/partials/home_page_content.html
-added 1px padding right to circle
-added 0.2rem extra on padding top for link
https://app.clickup.com/t/1hyt2d1
=> Mkj visual corrections 1hyt2d1

site_search/static/scss/search_landing.scss
=> fix the scss, as failing to release on pre-prod due to error

CMS/templates/robots.txt
update the domain in the robots.txt file
=> use the domain for robots.txt

core/request_handler.py, courses/templates/courses/course_detail_page.html, institutions/templates/institutions/institution_detail_page.html
=> Sjh #2jvrdrm descriptions

courses/templates/courses/partials/after_one_year_body.html, courses/templates/courses/partials/graduate_perceptions_body.html, courses/templates/courses/partials/student_satisfaction_body.html
changed it to be top aligned as per ticket- #2jvtprm
=> changed it to be top aligned - #2jvtprm

CMS/templates/base.html
=> comment out js for popup

CMS/static/scss/partials/popup.scss, CMS/templates/base.html, CMS/templates/partials/pop-up-about-data.html, CMS/templates/partials/pop-up-course-details.html
Fixing the mobile view and adding logic back in to popup
=> Mkj popup mobile view changes

CMS/static/scss/partials/popup.scss
fixing media query to not trigger on small laptop screen
=> Mkj fixing media query

CMS/static/scss/partials/popup.scss
=> positioning popup higher

CMS/static/scss/partials/popup.scss
added smallest mobilse size media query
=> added media query for even smaller phone width

CMS/translations/dictionaries/unavailable.py, courses/models/continuationstatistics.py, courses/models/employmentstatistics.py, courses/models/entrystatistics.py, courses/models/graduateperceptionstats.py, courses/models/satisfactionstats.py, courses/models/tariffstats.py, courses/models/utils.py
https://app.clickup.com/t/2cyufrn
- New course unavailable messages updated as per ticket. 
- View course comparison with AA course for architecture involved
- Hover over unavailable reason in one of the accordions
- It should have the new course message.
=> Ndp new course unavail #2cyufrn

CMS/static/js/search_box.js, CMS/templates/partials/new-search-dropdown.html, CMS/translations/dictionaries/unavailable.py, courses/models/continuationstatistics.py, courses/models/employmentstatistics.py, courses/models/entrystatistics.py, courses/models/graduateperceptionstats.py, courses/models/satisfactionstats.py, courses/models/tariffstats.py, courses/models/utils.py, courses/templates/courses/partials/earnings_after_the_course_body.html, courses/views/views.py, dev_tools/build_institutions_json_file/build_institutions_json_file.py
https://app.clickup.com/t/2rjwn9g
- Unavailable messages updated if salary agg = 21 or 22
=> Ndp new course unavail earnings

CMS/static/js/search_box.js, CMS/templates/partials/new-search-dropdown.html, CMS/translations/dictionaries/unavailable.py, courses/models/continuationstatistics.py, courses/models/course.py, courses/models/employmentstatistics.py, courses/models/entrystatistics.py, courses/models/graduateperceptionstats.py, courses/models/satisfactionstats.py, courses/models/tariffstats.py, courses/models/utils.py, courses/templates/courses/partials/earnings_after_the_course_body.html, courses/views/views.py, dev_tools/build_institutions_json_file/build_institutions_json_file.py, docker-compose.yml
https://app.clickup.com/t/2tn6apu
Hard coded years changed:
2010 - 2012 = 2011 - 2013
2017 - 2018 = 2018 - 2020
Load up the course details page and check the text reads either 2011 - 2013 or 2018-2020
=> Ndp hardcoded years updated

CMS/static/js/search_box.js, CMS/templates/partials/new-search-dropdown.html, CMS/translations/dictionaries/general.py, CMS/translations/dictionaries/unavailable.py, courses/models/continuationstatistics.py, courses/models/course.py, courses/models/employmentstatistics.py, courses/models/entrystatistics.py, courses/models/graduateperceptionstats.py, courses/models/satisfactionstats.py, courses/models/tariffstats.py, courses/models/utils.py, courses/templates/courses/partials/earnings_after_the_course_body.html, courses/views/views.py, dev_tools/build_institutions_json_file/build_institutions_json_file.py, docker-compose.yml
https://app.clickup.com/t/2tfadkx
Banner text updated on course details page
- Load course details page
- Read the banner
=> Ndp new banner text #2tfadkx

CMS/static/js/search_box.js, CMS/templates/partials/new-search-dropdown.html, CMS/translations/dictionaries/unavailable.py, courses/models/continuationstatistics.py, courses/models/employmentstatistics.py, courses/models/entrystatistics.py, courses/models/graduateperceptionstats.py, courses/models/satisfactionstats.py, courses/models/tariffstats.py, courses/models/utils.py, courses/templates/courses/partials/earnings_after_the_course_body.html, courses/views/views.py, dev_tools/build_institutions_json_file/build_institutions_json_file.py, docker-compose.yml
https://app.clickup.com/t/2rjwn9g
New course unavailable messages conditions on appearing updated. If salagg in 1, 2, 11, 12, 21, 22
=> Ndp new course unavail earnings #2rjwn9g

CMS/static/js/search_box.js, CMS/templates/partials/new-search-dropdown.html
Added legal and trading names to dropdown search
Await pre-prod data then try searching for an institutions legal name or other names
=> added required search changes to frontend

courses/models/salary.py
https://app.clickup.com/t/2u0qt9h
aggregate declared earlier to avoid error
=> declare aggregate earlier in code so page doesn't error

courses/models/salary.py, courses/templates/courses/partials/earnings_after_the_course_body.html, courses/templates/courses/partials/graduate_perceptions_body.html
- Unavailable message in salary and GO fixed
=> earnings unavailable fixed and GO override now displays when agg != 14

courses/models/graduateperceptionstats.py, courses/models/utils.py
https://app.clickup.com/t/2cyufrn
- Fix for the GO accordion unavailable messages 
- Run locally
- Go here: http://localhost:8000/course-details/10000291/K00092/Full-time/
- Check the unavailable message says "Because the course is new or has not been running long enough, there was not enough data to publish information specifically for this course. This does not reflect on the quality of the course."
=> Ndp new unavail fixes #2cyufrn

CMS/templates/partials/new-search-dropdown.html, courses/models/graduateperceptionstats.py, courses/models/utils.py
https://app.clickup.com/t/1p83f01
- Can now search Welsh institution names in the search dropdown menu
- Open the search dropdown
- Type in Prifysgol
- Check to see whether some results with Prifysgol appear
=> Ndp new search logic fix #1p83f01

CMS/templates/partials/new-search-dropdown.html, courses/models/graduateperceptionstats.py, courses/models/utils.py, courses/templates/courses/partials/employment_after_the_course_body.html
https://app.clickup.com/t/2kr7wbn
Employment unavailable messages now only don't appear if agg = 14
=> Ndp agg 24 fix

CMS/translations/dictionaries/general.py, courses/templates/courses/course_detail_content.html
https://app.clickup.com/t/2tfadkx
Welsh text added to leo banner
=> added welsh for leo banner

courses/models/course.py
changed more dates from 2010-1012 to 2011-2013 in earings after the course
=> updated more hardcoded dates from 2010-2012 to 2011-2013

CMS/static/scss/global.scss, CMS/translations/dictionaries/general.py, courses/models/course.py, courses/templates/courses/course_detail_content.html, courses/templates/courses/partials/course_overview.html, courses/views/views.py
https://app.clickup.com/t/32dmd7q
https://app.clickup.com/t/32dmb85
https://app.clickup.com/t/327r8r8
- Hard coded years changed from 2011 - 2013 to 2012 - 2014.
- Leo banner text updated to reflect new data - had to restyle on big screens as there is a lot more text and spilt outside of container
- Text in satisfaction box on course detail page updated
- Subject title updated in this box to match agg level
=> Ndp leo changes

CMS/translations/dictionaries/general.py
Removed duplicate "Please note"
=> removed duplicate please note

CMS/static/scss/global.scss
On hover text colour is now green on the leo banner
=> on hover text colour fix

courses/templates/courses/course_detail_content.html
=> comment out the leo banner

CMS/templates/robots.txt, coursefinder/templates/coursefinder/partials/active_filters.html, coursefinder/views.py, institutions/templates/institutions/institution_detail_page.html
Can now copy and paste a url with one institution and all of its courses
Go to institution detail page and click the view all courses button
=> Ndp shareable url

azure-pipelines.yml, dev-azure-pipelines.yml, holding-page-azure-pipelines.yml, pre-prod-azure-pipelines.yml, prod-azure-pipelines.yml
Update pipelines to build on the latest version of ubuntu
=> update to run on ubuntu latest

institutions/views.py
The 'en/cy/' in the nav url has been fixed on the institution detail page
Navigate to this link: http://localhost:8000/en/institution-details/10008071/
Inspect the welsh button and check the link reads "cy" and not "en/cy"
=> Ndp en cy url fix

coursefinder/templates/coursefinder/partials/active_filters.html
=> removed variable that prints out  institutions

CMS/templates/base.html, CMS/translations/dictionaries/general.py, cookie/static/cookie.js, cookie/templates/cookie-banner.html
Added in Welsh translations for cookies
Clear cookies locally, and run code checking setting and then saving cookie settings as well being happy to have cookies - will need to reset cookies each test
=> Sjh egxhdd cookie update

CMS/translations/dictionaries/general.py
welsh updated for cookie settings
=> welsh updated for cookie settings

cookie/static/cookie.js
fixes:[ #egxhdd](https://app.clickup.com/t/egxhdd) see comment on ticket
=> don't show cookie banner on cookie privacy polict page

CMS/translations/dictionaries/general.py, courses/templates/courses/course_detail_content.html, home/templates/home/home_page.html, manage.py
=> Ndp temporary banner

content/templates/content/section.html, courses/models/satisfactionstats.py, courses/templates/courses/new_course_details/partials/course_overview.html, courses/templates/courses/new_course_details/partials/student_satisfaction_body.html, courses/templates/courses/new_course_details/partials/summary_boxes/course_data_summary_average_earnings_box.html, courses/templates/courses/new_course_details/partials/summary_boxes/summary_source_grad.html, courses/unavail_dict_cy.py, courses/unavail_english_dict.py, courses/views/views.py
0% and £None fixes implemented, unavailable for NSS fixed
test with this link:
http://localhost:8000/course-details/10007856/FDSC_D402/Full-time/
University of x, the fixed - now displays the "The" first,
test with this link:
http://localhost:8000/course-details/10007154/N410/Full-time/
Popup removed on about our data
=> Ndp new data fixes

courses/models/satisfactionstats.py
=> unavail code fix

CMS/static/scss/partials/compare.scss, CMS/static/scss/partials/new_course_detail.scss, CMS/static/scss/partials/student_satisfaction.scss, courses/templates/courses/new_course_details/partials/course_summary.html, courses/templates/courses/new_course_details/partials/student_satisfaction_1_box.html, courses/templates/courses/new_course_details/partials/student_satisfaction_body.html, institutions/static/scss/institution_details.scss
#8692ybtu5
#8692ye49h
#8692ybqw3
=> #8692ybtu5, #8692ye49h, #8692ybqw3 - bugs fixed

CMS/static/scss/partials/earnings_after_course.scss, CMS/static/scss/partials/new_course_detail.scss, courses/templates/courses/new_course_details/partials/entry_information_body.html
8692ybp2t
https://app.clickup.com/t/8692ybp2t
=> https://app.clickup.com/t/8692ybp2t - fixed mobile sizing

courses/models/courseother.py, courses/templates/courses/new_course_details/partials/compare-popup-bar.html
keele fix and course popup link fix
=> Mkj 2023 updates

CMS/static/scss/partials/student_satisfaction.scss, CMS/static/scss/student_satisfaction.scss
changed random green text to blue colour (and font to plus jakarta sans)
=> fixed the green text

CMS/static/scss/accreditation.scss, CMS/static/scss/partials/compare.scss
updated css for professional accreditation
=> professional accreditation

institutions/static/scss/institution_details.scss, institutions/templates/institution/institution_detail.html
#86934cebx - https://app.clickup.com/t/86934cebx
removed the P tags with the unwanted text and adjusted css for remaining button
=> #86934cebx - remove course number text on institution page

CMS/translations/dictionaries/general.py, institutions/static/scss/institution_details.scss, institutions/templates/institution/institution_detail.html
changed text on instituition detail buttons
=> updated button text on institution_detail

core/templatetags/discover_uni_tags.py, courses/models/course.py, courses/templates/courses/new_course_details/partials/earnings_after_the_course_body.html
3 and 5 year data source updated
=> fixing leo source

courses/templates/courses/new_course_details/partials/earnings_after_the_course_body.html
all sources have the link icon
=> all sources have link icon

core/templatetags/discover_uni_tags.py, courses/templates/courses/new_course_details/partials/earnings_after_the_course_body.html
added if statement and handled none
=> fix for smb group bug

CMS/translations/dictionaries/general.py, courses/templates/courses/new_course_details/course_detail_content.html, courses/templates/courses/new_course_details/partials/employment_after_the_course_body.html
changed wording on bar charts ready for 21st feb ingestion - #8693u7h46 
https://app.clickup.com/t/8693u7h46
=> changed barchart wording for 21st feb - #8693u7h46

courses/models/satisfactionstats.py, courses/templates/courses/new_course_details/partials/student_satisfaction_1_box.html, courses/templates/courses/new_course_details/partials/student_satisfaction_body.html
- added try/except on lines causing 500 error
- added no_data_available key for mental wellbeing box
=> Glasgow caledonia fix

CMS/translations/dictionaries/statistics.py, courses/templates/courses/new_course_details/course_detail_content.html, courses/templates/courses/new_course_details/partials/student_satisfaction_body.html
- commented out banner
- glasgow caledonia fix with hidden mental health box
=> Mkj hide wellbeing

courses/templates/courses/new_course_details/partials/course_summary.html
missed the if agg 14/24 from graduate perceptions box
=> missed graduate perceptions box- now fixed

core/templatetags/discover_uni_tags.py, courses/templates/courses/new_course_details/course_detail_content.html, courses/templates/courses/new_course_details/partials/course_detail_information_banner.html
commented out banner put up in march
commented out logic to go with it
- didn't remove as we reuse this banner for any announcements needed
=> commented out banner and logic

CMS/templates/partials/footer.html
changed size of medr logo in footer
=> changes size of medr logo in footer

courses/templates/courses/course_comparison_page.html, courses/templates/courses/new_course_details/course_detail_page.html
=> changed file name

CMS/translations/dictionaries/general.py, core/templatetags/discover_uni_tags.py, courses/models/satisfactionstats.py, courses/static/js/bookmark_management.js, courses/templates/courses/new_course_details/partials/source.html, courses/templates/courses/new_course_details/partials/student_satisfaction_2_box.html, courses/templates/courses/new_course_details/partials/student_satisfaction_3_box.html, courses/templates/courses/new_course_details/partials/student_satisfaction_4_box.html, courses/templates/courses/new_course_details/partials/student_satisfaction_body.html, courses/templates/courses/new_course_details/partials/student_satisfaction_student_voice_box.html
- added titles to theme score
- removed fake data
- separated last question on student voice
- sorted out source
- fixed bug with empty subject
=> Mkj data 2024

CMS/translations/dictionaries/general.py
removed a stray } from translation
=> removed a stray }

courses/templates/courses/partials/comparison_courses_row.html
=> missed it off for welsh

courses/models/course.py, courses/templates/courses/new_course_details/partials/earnings_after_the_course_body.html
updated the after 1 year year from 2020-21 to 2021-2022
=> 2021 updated to 2022

courses/templates/courses/new_course_details/partials/earnings_after_the_course_body.html
=> removed rogue letters

courses/templates/courses/new_comparison/comparison_overall_donut_row.html
forgot to commit change for teaching data
=> forgot to add teaching change

courses/static/js/bookmark_management.js, courses/templates/courses/new_comparison/comparison_courses_row_donut.html, courses/templates/courses/new_comparison/comparison_overall_donut_row.html, courses/templates/courses/new_course_details/partials/unavailable.html, courses/templates/courses/partials/comparison_courses_row.html, courses/templates/courses/partials/unavailable.html
fixed subject switcher in course comparison
had whitespace in class where page was formatted
added colum-1National Student Survey item-1 sub- div that subject switcher was looking for on theme donuts
=> Mkj adding themes

core/utils.py, courses/renderer/comparison.py, courses/renderer/sections/course_details.py, courses/views/comparison_body.py
if course doesnt exist when trying to compare courses, course gets deleted from list
=> course comparison page loads if error

courses/views/comparison_body.py
=> removed pprint import

courses/static/js/bookmark_management.js
changed 
(this.data.mode.en === 'Full time' || 'Full-time') and else if (this.data.mode.en === 'Part time' || 'Part-time')
to 
`${this.data.mode.en.replace(" t", "t").replace("-t", "t").replace("time", "Time")}`
as this.data.mode.en was coming through as "Part time" but still going down FullTime route
Also added in functionality where it calls the url for the course in saved courses and if it redirects, it doesnt render the course and also deletes it from local storage
=> fixed partTime url showing as fullTime

courses/static/js/bookmark_management.js
course comp showing 0 years instead of length of course not available
=> sets course length to correct value not 0 years

CMS/translations/dictionaries/general.py, courses/models/continuationstatistics.py, courses/renderer/sections/continuation.py, courses/templates/courses/new_course_details/partials/after_one_year_body.html, courses/templates/courses/partials/after_one_year_body.html
Fixes https://app.clickup.com/t/8696uzd13
- Removed "Taking a break from study" on course detail and course comparison page as data is to be combined into another statistic "Taking a break or left without a qualification"
=> Fixes https://app.clickup.com/t/8696uzd13 - Update "After 1 year" Data

courses/static/js/bookmark_management.js
Fixed solution for deleting invalid courses from bookmarked courses - courses are now removed from courses to compare.
=> Remove invalid bookmarks fix

CMS/translations/dictionaries/general.py, CMS/translations/dictionaries/statistics.py, courses/templates/courses/new_course_details/partials/student_satisfaction_body.html, courses/templates/courses/partials/info_box.html
Fixes https://app.clickup.com/t/86974wcjq - as requested by OfS
Updated NSS results data points and added full stop to entry information bullet point.
=> Update NSS data points

widget/v2_urls.py
=> remove new widget endpoints
