courses/models.py
courses/templates/courses/partials/after_the_course_body.html
courses/templates/courses/partials/entry_information_body.html

These include:
- Fix percentage for working or studying
- Fix 3years after the course to populate the correct number of students
- Fix Course details page -course title to include honours
- Fix number of students in ucas tariff stats
- Do not show earnings after 3years if no stats
Check changes results in the above changes

Several fixes on course details page

---

courses/templates/courses/course_detail_content.html

Hide empty links
Check the links at the bottom of the course details page are gone (only links that work should be visible)

Comment out further course details as links are currently empty

---

courses/models.py
widget/static/js/widget.js

The widget now adds the welsh extension in to its links if it is a welsh widget.
load a widget with cy-GB as the language param. The url provided on the button should be domain_name/cy/course_details/etc.

welsh widgets should send the users to welsh pages

---

widget/static/js/widget.js
widget/urls.py

handle the ~ character in widget urls
Go to <domain name>/widget/10007850/UUUH1-G400~USCM-AFB06/horizontal/small/en-GB/FullTime/
The widget should load correctly.

handle tilda in widget urls

---

core/templatetags/discover_uni_tags.py

If key for translations isn't present in the translations dict, use the key instead.
Go to a course page and all the common jobs should have labels.

fall back to the key if not in dict

---

CMS/static/js/main.js

Remove the quotes around the subject codes on search.
Go to the coursefinder and pick computing in the first 2 subject dropdowns. You should see results on the results page and only for the computing courses.

don't put quotes around the subject codes

---

courses/static/js/course_comparison.js

Removed some incompatibilities with IE and safari.
Open the compare page in IE or safari and you should be able to select a course to compare and have it display.

make compare IE11 compatible

---

CMS/static/js/main.js

Make the subject selector IE compatible
In IE go to the subject selector page of the course finder.
You should now be able to select a subject.

fix subject selector for IE11

---

CMS/static/js/main.js

Fixed issue of empty/missing drop-downs on course-finder-choose-subject screen when hitting back on the browser to this screen

fix to empty drop-down after back button press

---

CMS/static/js/main.js

Allow the user to clear subject options picked.
Go to the subject selector in the course finder.
Select an option at either level.
You should then be able to reselect the default option again to clear your choice.

allow for clearing of selection at each level

---

courses/static/scss/course_comparison.scss

Put the correct width CSS in for compare dropdowns on desktop.
Go to the comparison page and click on one of the two dropdowns.
The dropdown should stay within the container.

fix dropdown width on desktop

---

site_search/models.py
site_search/templates/site_search/search_landing_page.html

Remove second get_context method as it was overwriting the first and params were being lost.
Go to the search landing page, you should now be able to submit a search term and be taken to the results page.

there should be only one get context method

---

CMS/settings/base.py
docker-compose.yml
widget/views.py

Load the domain name from settings rather than db.
Read the changes. Try loading the widget, it should load correctly.

remove calls to the db in the widget loading

---

widget/views.py

Fixed issue with kis_mode being always set to default FullTime by making the comparison strings lowercase.

Fix for widget ignoring Part Time courses.

---

CMS/static/js/main.js

Using local storage with the cookies to ensure it sets correctly and doesn't show the banner more than once.
Clear cookies.
Load the site.
Accept the cookies.
Go to a new page.
The banner should not show again.

Cookie banner showing even after excepting

---

widget/static/js/widget.js

Fixed widged displaying [object Object] at the bottom instead of university name.
https://www.discoveruni.gov.uk/Widget/10007783/G120/horizontal/small/en-GB/
https://www.discoveruni.gov.uk/Widget/10007163/U-Q300/horizontal/small/en-GB/
Run wagtail on localhost. Check the widged displays university name using the example links:
http://localhost:8000/Widget/10007783/G120/horizontal/small/en-GB/
http://localhost:8000/Widget/10007163/U-Q300/horizontal/small/en-GB/

Fix to widget display issue.

---

CMS/static/jsonfiles/institutions_cy.json

Change "Bridgend College" to "Coleg Penybont" in the `CMS/static/jsonfiles/institutions_cy.json` file
Switch to the english version of the site. In the institutions drop-down search for "bridge". "Bridgend College" Should show up in the search results.
Switch to the welsh version of the site. In the institutions drop-down search for "peny". "Coleg Penybont" Should show up in the search results.
*(conduction a full search for "Coleg Penybont" will not work yet as all the courses for Bridgend College still have "Bridgend College" as the welsh name for them. A static entry has been added to `ukrpl_static` but a new ingestion has to be run to pick this up)*

added Bridgend College fix to institutions_cy.json

---

coursefinder/forms.py
coursefinder/templates/coursefinder/partials/filters.html

Added the postcode value as a default to an input on the filters form
1. Start a search query using the Course Finder Wizard
2. Select to search by postcode, and use 'WC1H0XG' within 50 miles.
3. The first page of the search results will be filtered correctly. At the bottom of the page, click to change to page 2 or 3.
4. Confirm that the only institutions being shown are in London

fixed postcode bug

---

courses/models.py

Change the default behaviour of the locations for course model so it falls back to english if a welsh name does not exist
Load up the page for a course in welsh and see if the location for the course is there underneath the name of the course/institution

FIXED: institute location now showing on welsh page for institution

---

CMS/static/scss/partials/filters.scss

Changed overflow for .filters-wrapper to visible to allow for sticky positioning.
added position: -webkit-sticky; position: sticky; to the submit class.
Removed the white background so the button can float neatly above the filters.

Sticky apply filter button

---

coursefinder/templates/coursefinder/partials/active_filters.html

Fix for closing currently active filters using pills.
Rather than submitting a value to the form directly, the JS unchecks the filter and sends the form

close active pill fix

---

coursefinder/templates/coursefinder/partials/active_filters.html

JS function updated:
if the on campus filter is closed using the filter pill, and the distance learning filter is still active, all regional filters are disabled.

regional filters removed if distance and not campus

---

CMS/templates/partials/course_result.html
CMS/templates/partials/institution_result.html
coursefinder/views.py

A "distance learning" label is added to the results accordions if they only contain distance learning courses, or optional distance learning courses from a region outside of what has been filtered.

distance learning accordion label

---

CMS/static/scss/partials/filters.scss
CMS/templates/partials/new-search-dropdown.html
CMS/translations.py
coursefinder/static/js/active-filter-pills.js
coursefinder/templates/coursefinder/partials/active_filters.html
coursefinder/views.py
home/templates/partials/home_page_content.html

The following changes have been made: 
Required:
1. Select all no counts already selected checkboxes
2. Welsh translations added
Optional:
1. Space added between the display names of institutions in the dropdown box
2. Clicking outside of the dropdown closes it automatically
3. Text changes if search input isn't blank
4. Dropdown box shrinks to fit the search query
5. Dropdown no longer pushes the accordions down a few pixels
6. Homepage header corrected and translation applied.

institution dropdown required and optional fixes

---

CMS/static/js/filters.js
coursefinder/forms.py
coursefinder/templates/coursefinder/partials/active_filters.html
coursefinder/templates/coursefinder/partials/location_filters.html
coursefinder/views.py

The apply filters button needs to be disabled if either postcode field is blank. JS has been fixed so that if distance learning is checked and on campus isn't, the button is enabled. Just ticking on campus no longer disables the button.
Added JS to enable the button before sending the form so that a load error doesn't occur.
The postcode is now sent through a form, rather than just query params - the form values are preserved and pre-filled into the postcode form on page load.
Region radio button is now checked on load by default -  the postcode radio  is checked and div is preloaded if the user filtered with a postcode.

F76egb learning filters on campus

---

CMS/templates/partials/course_result.html

Corrected function to use an if else statement, the distance learning label should now be correctly applied to "optionally available through distance learning".
Added an if statement to avoid any confusion over said labels when a postcode filter has been applied.

distance label fix

---

CMS/static/js/filters.js
CMS/static/scss/partials/filters.scss

Border turns red and apply button is disabled when only one of the postcode fields is filled in and the postcode radio button is checked.

postcode filter changes

---

CMS/static/js/filters.js
CMS/static/scss/partials/filters.scss
coursefinder/templates/coursefinder/partials/location_filters.html

Option tags are unable to be styled, and when viewed on smaller screens, the the text on the distance dropdowns on the postcode filter was too large.
This has been redone so that a separate dropdown now picks the option, which is now hidden, and has been styled to match the other dropdown menus on the site.
The JS that was originally effecting the distance select dropdown now also effects the new dropdown.

G95r2y postcode filter

---

CMS/translations.py
coursefinder/templates/coursefinder/partials/active_filters.html
coursefinder/views.py

Institution filter pills are no longer rendered via JS, and rather through a Django context variable. Because of this, the remove filter pill will always appear last.

remove filters always last

---

courses/static/js/bookmark_management.js
courses/templates/courses/course_manage_page.html

On 1st load the placeholder element for the bookmark'd courses was visible.
run the code, and clear you cached. If you have fast connection, you've probably never seen the issue. Disabled JS in the browser and refresh the page, should see nothing but the page headings.

hide placeholder content so it's not seen by the user

---

CMS/static/scss/partials/compare.scss
courses/static/js/back-button.js
courses/static/scss/course_detail.scss
courses/templates/courses/partials/course_overview.html

- Set z-index on #sticky_nav_course_detail to 10 to override bootstrap 1020 for sticky header.

fixes sticky header behind nav dropdown

---

CMS/templates/partials/course_result.html
CMS/translations/dictionaries/general.py
CMS/translations/dictionaries/unavailable.py
courses/models/utils.py
courses/static/js/bookmark_management.js
courses/templates/courses/partials/compare-popup-bar.html

- Compare popup now appears in Welsh
- The link for the course detail page now takes you to the Welsh page if the page is Welsh.
- Updated "Compare courses" title
- Updated Welsh translations for unavailable messages.

Translation fixes

---

CMS/templates/base.html

https://app.clickup.com/t/mzcp12
Once in prod- tabs doubled up '| discover uni' - removed suffix in base

fixing double '| discover uni' problem once in prod #mzcp12

---

courses/models/course.py

https://app.clickup.com/t/2tn6apu
Instances of 2011 - 2013 reverted back to 2010 - 2012
Go onto the course details page and make sure it reads 2010 - 2012 in the earnings section for after 3 years and after 5 years.

Ndp hardcoded years updated #2tn6apu

---

CMS/static/js/popup.js
CMS/static/scss/global.scss
CMS/templates/base.html
content/templates/content/section.html
courses/templates/courses/course_detail_page.html

https://app.clickup.com/t/2r7f4un
scss from about our data and course details popup was imported into global.scss so was spilling into the search filters code and causing visual bugs. Refactored the popup code to only be included on the relevant pages.
- On mobile view, navigate to the search page and click on show filters to check it is now displaying correctly
- On any view, navigate to a course details page from a different website - check the popup shows
- On any view navigate to the about our data page by clicking the link in NSS accordion and check the popup shows

Ndp fix search filter #2r7f4un

---

courses/models/satisfactionstats.py
courses/templates/courses/new_course_details/partials/earnings_after_the_course_body.html
courses/templates/courses/new_course_details/partials/student_satisfaction_body.html
courses/templates/courses/new_course_details/partials/summary_boxes/course_data_summary_average_earnings_box.html

- [Subject] in student satisfaction section replaced with the actual subject name
- Removed random message that shouldn't be there in earnings accordion
- Hide Q28 if there is no data and no other satisfaction data
- Leo messaging updated if using Leo3 in summary boxes

Ndp new data fixes

---

courses/models/utils.py

Ingested data appears to have no unavail message, update code to handle this scenario
Issue has come up: Open University has found that one of its courses (PUBUKPRN: 10007773, KISCOURSE: Q77) is listed in DU but returns 'Internal Server Error' when try to open course page.  I've checked the dataset and core info is there so it should be displaying.  Can you check it out? [Internal server error (discoveruni.gov.uk)](https://www.discoveruni.gov.uk/course-details/10007773/Q77/Part-time/)
Run the changes locally and visit the page and check the data is correct in the student satisfaction section

Fix DU course page identified as crashing
